batch_size: -1
experiment_id: generalization
dataset: nature
lr: 0.001
lr_decay: 1.
device: cuda
filters: 
  - fourier
  - gabor
  - siren_like
network_specs: 
-
  - 1
  - 256
-
  - 1
  - 512
-
  - 4
  - 256
input_scale: 128.
no_skip_solver: false
max_train_iters: 2000
log_freq: 50
verbose: false
continue_run: false