model_type: implicit
gabor_alpha: 3.0
forward_solver: forward_iter
backward_solver: onestep
lr: 0.001
filter_type: fourier
n_layers: 1
interm_channels: 2048
use_implicit: true
norm_type: none
input_scale: 256
experiment_id: DEQ-fourier-1L2048D
