model_type: implicit
gabor_alpha: 3.0
forward_solver: forward_iter
backward_solver: onestep
lr: 0.001
filter_type: gabor
n_layers: 4
interm_channels: 256
use_implicit: false
norm_type: none
input_scale: 25000.0
experiment_id: gabor-4L256D
